#!/bin/sh

osascript <<EOF
set ToAddresses to {"amuller@redhat.com","lpeer@redhat.com"}
set SelfAddress to "ihrachys@redhat.com"
set theSubject to "Weekly status"
set theContent to do shell script "~/bin/weekly-report.sh"

tell application "Mail"
    set theMessage to make new outgoing message with properties {subject:theSubject, content:theContent, visible:true}
    tell theMessage
        repeat with i from 1 to count ToAddresses
            make new to recipient at end of every to recipient with properties {address:item i of ToAddresses}
        end repeat
        make new bcc recipient with properties {address:SelfAddress}
        send
    end tell
end tell
